# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Roaming Home')),
                ('venue', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(help_text='e.g. 3 hours, 5 days', max_length=20)),
            ],
        ),
    ]
